version: "3"
services:
  logger:
    image: chentex/random-logger:latest
    restart: always
    container_name: logger
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
